const nome = "Anna";
let idade = 17;
const curso = "Eletromecânica";
const matriculado = true;
const nome = "João";
console.log(nome);
console.log(idade);
console.log(curso);
console.log(matriculado);
console.log("Nome:", nome);
console.log("Idade:", idade);
console.log("Curso:", curso);
console.log("Está matriculado?", matriculado);